 Container viniciusfcf-db-1  Running
 Container viniciusfcf-api02-1  Running
 Container viniciusfcf-api01-1  Running
 Container viniciusfcf-nginx-1  Running
Attaching to api01-1, api02-1, db-1, nginx-1
 Container viniciusfcf-api02-1  Stopped
 Container viniciusfcf-api01-1  Stopped
 Container viniciusfcf-db-1  Stopping
api02-1 exited with code 0
api01-1 exited with code 0
api02-1 exited with code 137
api01-1 exited with code 137
db-1     | 2024-02-13 00:26:53.999 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-13 00:26:53.999 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-13 00:26:54.004 UTC [1] LOG:  background worker "logical replication launcher" (PID 32) exited with exit code 1
db-1     | 2024-02-13 00:26:54.004 UTC [27] LOG:  shutting down
db-1     | 2024-02-13 00:26:54.004 UTC [27] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-13 00:26:54.008 UTC [27] LOG:  checkpoint complete: wrote 445 buffers (2.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=2623 kB, estimate=2623 kB; lsn=0/73755F8, redo lsn=0/73755F8
db-1     | 2024-02-13 00:26:54.014 UTC [1] LOG:  database system is shut down
 Container viniciusfcf-db-1  Stopped
db-1 exited with code 0
db-1 exited with code 0
nginx-1  | 2024/02/13 00:26:55 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:26:55 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8082/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:26:57 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:26:59 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:01 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:03 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:05 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:07 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8082/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:07 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:09 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:11 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:13 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:15 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:17 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:19 [error] 29#29: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8082/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:19 [error] 29#29: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:21 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:23 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:25 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:27 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:29 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:31 [error] 29#29: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8082/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:31 [error] 29#29: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 00:27:34 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
canceled
nginx-1 exited with code 0
