 Network brunolipe-a_rinha-network  Creating
 Network brunolipe-a_rinha-network  Created
 Container brunolipe-a-db-1  Creating
 Container brunolipe-a-db-1  Created
 Container brunolipe-a-api01-1  Creating
 Container brunolipe-a-api02-1  Creating
 Container brunolipe-a-api01-1  Created
 Container brunolipe-a-api02-1  Created
 Container brunolipe-a-nginx-1  Creating
 Container brunolipe-a-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start.... done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1     | 
api02-1  | {"level":30,"time":1708219495631,"pid":1,"hostname":"api02","msg":"started HTTP server on 0.0.0.0:3333"}
api01-1  | [ error ] connect ECONNREFUSED 192.168.64.2:5432
api01-1  |           at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
db-1     | waiting for server to shut down.... done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
api01-1 exited with code 1
nginx-1  | 2024/02/18 01:25:00 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3333/clientes/1/extrato", host: "localhost:9999"
api02-1  | {"level":50,"time":1708219500618,"pid":1,"hostname":"api02","request_id":"bcpwe12srm5ua9s00cwn8li5","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"bcpwe12srm5ua9s00cwn8li5","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219502631,"pid":1,"hostname":"api02","request_id":"v8so2p0y6sgvp1sadhr6yy7l","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"v8so2p0y6sgvp1sadhr6yy7l","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219504641,"pid":1,"hostname":"api02","request_id":"o8j2v6ct1fh4qem2vyxmjlfd","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"o8j2v6ct1fh4qem2vyxmjlfd","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219506650,"pid":1,"hostname":"api02","request_id":"ghht1xcyf7l91jvr72qu1s0e","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"ghht1xcyf7l91jvr72qu1s0e","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219508659,"pid":1,"hostname":"api02","request_id":"oy6m22dehdcoi0ioxpp1ovsv","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"oy6m22dehdcoi0ioxpp1ovsv","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219510668,"pid":1,"hostname":"api02","request_id":"tgyuktw3xmb2tv2kbxr7r48m","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"tgyuktw3xmb2tv2kbxr7r48m","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219512677,"pid":1,"hostname":"api02","request_id":"tyy87mtdohxj5ktn4xyfb7v6","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"tyy87mtdohxj5ktn4xyfb7v6","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219514687,"pid":1,"hostname":"api02","request_id":"cbsnigwkxi3xzj30lq4xrv17","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"cbsnigwkxi3xzj30lq4xrv17","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
nginx-1  | 2024/02/18 01:25:19 [error] 29#29: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3333/clientes/1/extrato", host: "localhost:9999"
api02-1  | {"level":50,"time":1708219519757,"pid":1,"hostname":"api02","request_id":"c811mls86vtnh4egbiwztvrh","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"c811mls86vtnh4egbiwztvrh","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219521768,"pid":1,"hostname":"api02","request_id":"v9ccaw37hoa9irn9hbhbbyqt","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"v9ccaw37hoa9irn9hbhbbyqt","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219523777,"pid":1,"hostname":"api02","request_id":"yosujdfz3codazc9u3g6o2il","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"yosujdfz3codazc9u3g6o2il","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219525786,"pid":1,"hostname":"api02","request_id":"d9v4lqup91hal0kr2g7q10bk","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"d9v4lqup91hal0kr2g7q10bk","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219527795,"pid":1,"hostname":"api02","request_id":"qiawewgr9abtnft8p4ic17n6","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"qiawewgr9abtnft8p4ic17n6","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219529804,"pid":1,"hostname":"api02","request_id":"k2wekb00do9o7jspr9w3rmgw","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"k2wekb00do9o7jspr9w3rmgw","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219531812,"pid":1,"hostname":"api02","request_id":"nari852kf1zpv1n6kdl9goiv","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"nari852kf1zpv1n6kdl9goiv","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219533821,"pid":1,"hostname":"api02","request_id":"pilf6p74bozg0bynuz6o3pib","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"pilf6p74bozg0bynuz6o3pib","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
nginx-1  | 2024/02/18 01:25:38 [error] 29#29: *35 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3333/clientes/1/extrato", host: "localhost:9999"
api02-1  | {"level":50,"time":1708219538892,"pid":1,"hostname":"api02","request_id":"dlzx1flzg3c7x8lmyqgs0a72","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"dlzx1flzg3c7x8lmyqgs0a72","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219540902,"pid":1,"hostname":"api02","request_id":"w8jvw6qzu4dllr16qqr9pgxy","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"w8jvw6qzu4dllr16qqr9pgxy","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219542910,"pid":1,"hostname":"api02","request_id":"pkhjl58y8gy7vqtbaz1h4gin","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"pkhjl58y8gy7vqtbaz1h4gin","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
api02-1  | {"level":50,"time":1708219544919,"pid":1,"hostname":"api02","request_id":"ddo5cahco5le8iszg37apg66","err":{"type":"DatabaseError","message":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist","stack":"error: select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":106,"name":"error","severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1449","routine":"parserOpenTable","status":500},"x-request-id":"ddo5cahco5le8iszg37apg66","msg":"select * from \"clients\" where \"id\" = $1 limit $2 - relation \"clients\" does not exist"}
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1 exited with code 0
api02-1 exited with code 0
db-1 exited with code 0
