 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container db  Creating
 Container db  Created
 Container api02  Creating
 Container api01  Creating
 Container api01  Created
 Container api02  Created
 Container oneabrante-nginx-1  Creating
 Container oneabrante-nginx-1  Created
Attaching to api01, api02, db, nginx-1
db       | The files belonging to this database system will be owned by user "postgres".
db       | This user must also own the server process.
db       | 
db       | The database cluster will be initialized with locale "en_US.utf8".
db       | The default database encoding has accordingly been set to "UTF8".
db       | The default text search configuration will be set to "english".
db       | 
db       | Data page checksums are disabled.
db       | 
db       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db       | creating subdirectories ... ok
db       | selecting dynamic shared memory implementation ... posix
db       | selecting default max_connections ... 100
db       | selecting default shared_buffers ... 128MB
db       | selecting default time zone ... Etc/UTC
db       | creating configuration files ... ok
db       | running bootstrap script ... ok
db       | performing post-bootstrap initialization ... ok
api02    | 
api02    | > rinha_backend_2024@1.0.0 dev
api02    | > nodemon src/index.js
api02    | 
api01    | 
api01    | > rinha_backend_2024@1.0.0 dev
api01    | > nodemon src/index.js
api01    | 
api02    | [33m[nodemon] 3.1.0[39m
api02    | [33m[nodemon] to restart at any time, enter `rs`[39m
api02    | [33m[nodemon] watching path(s): *.*[39m
api02    | [33m[nodemon] watching extensions: js,mjs,cjs,json[39m
api02    | [32m[nodemon] starting `node src/index.js`[39m
api01    | [33m[nodemon] 3.1.0[39m
api01    | [33m[nodemon] to restart at any time, enter `rs`[39m
api01    | [33m[nodemon] watching path(s): *.*[39m
api01    | [33m[nodemon] watching extensions: js,mjs,cjs,json[39m
api01    | [32m[nodemon] starting `node src/index.js`[39m
api02    | Ouvindo na porta 3000
api01    | Ouvindo na porta 3000
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api02 exited with code 137
api01 exited with code 137
db       | syncing data to disk ... ok
db       | 
db       | 
db       | Success. You can now start the database server using:
db       | 
db       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db       | 
db       | initdb: warning: enabling "trust" authentication for local connections
db       | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db       | waiting for server to start....2024-03-03 01:43:57.569 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db       | 2024-03-03 01:43:57.572 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db       | 2024-03-03 01:43:57.582 UTC [51] LOG:  database system was shut down at 2024-03-03 01:43:55 UTC
db       | 2024-03-03 01:43:57.587 UTC [48] LOG:  database system is ready to accept connections
db       |  done
db       | server started
db       | CREATE DATABASE
db       | 
db       | 
db       | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db       | CREATE TABLE
db       | CREATE TABLE
db       | ALTER TABLE
db       | INSERT 0 5
db       | 
db       | 
db       | waiting for server to shut down....2024-03-03 01:43:57.801 UTC [48] LOG:  received fast shutdown request
db       | 2024-03-03 01:43:57.803 UTC [48] LOG:  aborting any active transactions
db       | 2024-03-03 01:43:57.805 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db       | 2024-03-03 01:43:57.806 UTC [49] LOG:  shutting down
db       | 2024-03-03 01:43:57.809 UTC [49] LOG:  checkpoint starting: shutdown immediate
db       | 2024-03-03 01:43:58.288 UTC [49] LOG:  checkpoint complete: wrote 938 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.363 s, sync=0.083 s, total=0.483 s; sync files=310, longest=0.054 s, average=0.001 s; distance=4301 kB, estimate=4301 kB; lsn=0/191E050, redo lsn=0/191E050
db       | 2024-03-03 01:43:58.292 UTC [48] LOG:  database system is shut down
db       |  done
db       | server stopped
db       | 
db       | PostgreSQL init process complete; ready for start up.
db       | 
db       | 2024-03-03 01:43:58.324 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db       | 2024-03-03 01:43:58.324 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db       | 2024-03-03 01:43:58.324 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db       | 2024-03-03 01:43:58.330 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db       | 2024-03-03 01:43:58.337 UTC [66] LOG:  database system was shut down at 2024-03-03 01:43:58 UTC
db       | 2024-03-03 01:43:58.344 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/03/03 01:44:01 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:04 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:06 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:08 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:10 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:15 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:18 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:20 [error] 29#29: *10 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:22 [error] 29#29: *11 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:24 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:29 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:32 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:34 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:36 [error] 29#29: *17 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:38 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:43 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:47 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:49 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:51 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:53 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:44:58 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:01 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:03 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:05 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:07 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db       | 2024-03-03 01:45:09.910 UTC [1] LOG:  received fast shutdown request
db       | 2024-03-03 01:45:09.914 UTC [1] LOG:  aborting any active transactions
db       | 2024-03-03 01:45:09.916 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db       | 2024-03-03 01:45:09.916 UTC [64] LOG:  shutting down
db       | 2024-03-03 01:45:09.921 UTC [64] LOG:  checkpoint starting: shutdown immediate
db       | 2024-03-03 01:45:09.960 UTC [64] LOG:  checkpoint complete: wrote 46 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.020 s, total=0.044 s; sync files=14, longest=0.017 s, average=0.002 s; distance=94 kB, estimate=94 kB; lsn=0/1935850, redo lsn=0/1935850
db       | 2024-03-03 01:45:09.963 UTC [1] LOG:  database system is shut down
db exited with code 0
