 Container lucianovilela-db-1  Creating
 Container lucianovilela-db-1  Created
 Container lucianovilela-api02-1  Creating
 Container lucianovilela-api01-1  Creating
 Container lucianovilela-api02-1  Created
 Container lucianovilela-api01-1  Created
 Container lucianovilela-nginx-1  Creating
 Container lucianovilela-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api01-1  | Erro ao conectar com o banco de dados 2024-02-19T10:54:35.157Z
api02-1  | Erro ao conectar com o banco de dados 2024-02-19T10:54:35.219Z
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
api01-1  | Erro ao conectar com o banco de dados 2024-02-19T10:54:37.162Z
api02-1  | Erro ao conectar com o banco de dados 2024-02-19T10:54:37.224Z
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-19 10:54:37.332 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-19 10:54:37.336 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-19 10:54:37.348 UTC [51] LOG:  database system was shut down at 2024-02-19 10:54:36 UTC
db-1     | 2024-02-19 10:54:37.355 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-02-19 10:54:37.719 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-19 10:54:37.722 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-19 10:54:37.724 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-19 10:54:37.725 UTC [49] LOG:  shutting down
db-1     | 2024-02-19 10:54:37.728 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-19 10:54:38.192 UTC [49] LOG:  checkpoint complete: wrote 944 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.201 s, sync=0.241 s, total=0.467 s; sync files=310, longest=0.217 s, average=0.001 s; distance=4313 kB, estimate=4313 kB; lsn=0/19211D8, redo lsn=0/19211D8
db-1     | 2024-02-19 10:54:38.197 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-19 10:54:38.245 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-19 10:54:38.245 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-19 10:54:38.245 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-19 10:54:38.251 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-19 10:54:38.259 UTC [66] LOG:  database system was shut down at 2024-02-19 10:54:38 UTC
db-1     | 2024-02-19 10:54:38.266 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/19 10:54:38 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:38 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
api01-1  | Conexão com o banco de dados estabelecida com sucesso
api01-1  | Servidor rodando na porta 9000
api02-1  | Conexão com o banco de dados estabelecida com sucesso
api02-1  | Servidor rodando na porta 9001
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *12 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *13 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *14 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *15 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *16 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *9 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *10 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *11 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *21 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *22 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *23 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *24 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *25 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *17 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *18 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:45 [error] 30#30: *20 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:47 [error] 30#30: *64 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/02/19 10:54:49 [error] 30#30: *152 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/5/extrato HTTP/1.1", upstream: "http://api/clientes/5/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api01-1 exited with code 0
api01-1 exited with code 137
api02-1 exited with code 0
api02-1 exited with code 137
db-1     | 2024-02-19 10:59:03.559 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-19 10:59:03.563 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-19 10:59:03.565 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-19 10:59:03.566 UTC [64] LOG:  shutting down
db-1     | 2024-02-19 10:59:03.568 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-19 10:59:03.698 UTC [64] LOG:  checkpoint complete: wrote 617 buffers (3.8%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.009 s, sync=0.104 s, total=0.133 s; sync files=32, longest=0.066 s, average=0.004 s; distance=19943 kB, estimate=19943 kB; lsn=0/2C9AFC0, redo lsn=0/2C9AFC0
db-1     | 2024-02-19 10:59:03.702 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
