 Container krymancer-db-1  Creating
 Container krymancer-db-1  Created
 Container krymancer-api2-1  Creating
 Container krymancer-api1-1  Creating
 Container krymancer-api1-1  Created
 Container krymancer-api2-1  Created
 Container krymancer-nginx-1  Creating
 Container krymancer-nginx-1  Created
Attaching to api1-1, api2-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
api1-1   | info: Microsoft.Hosting.Lifetime[14]
api1-1   |       Now listening on: http://0.0.0.0:3000
api1-1   | info: Microsoft.Hosting.Lifetime[0]
api1-1   |       Application started. Press Ctrl+C to shut down.
api1-1   | info: Microsoft.Hosting.Lifetime[0]
api1-1   |       Hosting environment: Production
api1-1   | info: Microsoft.Hosting.Lifetime[0]
api1-1   |       Content root path: /app
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
api2-1   | info: Microsoft.Hosting.Lifetime[14]
api2-1   |       Now listening on: http://0.0.0.0:3001
api2-1   | info: Microsoft.Hosting.Lifetime[0]
api2-1   |       Application started. Press Ctrl+C to shut down.
api2-1   | info: Microsoft.Hosting.Lifetime[0]
api2-1   |       Hosting environment: Production
api2-1   | info: Microsoft.Hosting.Lifetime[0]
api2-1   |       Content root path: /app
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-02-20 03:23:10.194 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-20 03:23:10.197 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-20 03:23:10.207 UTC [51] LOG:  database system was shut down at 2024-02-20 03:23:08 UTC
db-1     | 2024-02-20 03:23:10.213 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | CREATE INDEX
db-1     | INSERT 0 5
db-1     | CREATE FUNCTION
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/postgresql.conf
db-1     | 
db-1     | waiting for server to shut down...2024-02-20 03:23:10.453 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-20 03:23:10.461 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-20 03:23:10.463 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-20 03:23:10.463 UTC [49] LOG:  shutting down
db-1     | 2024-02-20 03:23:10.467 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-20 03:23:11.032 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.394 s, sync=0.156 s, total=0.569 s; sync files=308, longest=0.070 s, average=0.001 s; distance=4292 kB, estimate=4292 kB; lsn=0/191BC80, redo lsn=0/191BC80
db-1     | 2024-02-20 03:23:11.038 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-20 03:23:11.078 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-20 03:23:11.078 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-20 03:23:11.078 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-20 03:23:11.084 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-20 03:23:11.091 UTC [66] LOG:  database system was shut down at 2024-02-20 03:23:11 UTC
db-1     | 2024-02-20 03:23:11.099 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/20 03:23:12 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:14 [error] 21#21: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:16 [error] 22#22: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:18 [error] 23#23: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:20 [error] 20#20: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:22 [error] 20#20: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:24 [error] 20#20: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:26 [error] 20#20: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:28 [error] 20#20: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:30 [error] 20#20: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:32 [error] 20#20: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:34 [error] 20#20: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:36 [error] 20#20: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:38 [error] 20#20: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:40 [error] 20#20: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:42 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:44 [error] 20#20: *33 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:46 [error] 20#20: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:48 [error] 20#20: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 03:23:50 [error] 20#20: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:80/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api1-1   | info: Microsoft.Hosting.Lifetime[0]
api1-1   |       Application is shutting down...
api2-1   | info: Microsoft.Hosting.Lifetime[0]
api2-1   |       Application is shutting down...
api1-1 exited with code 0
api2-1 exited with code 0
api2-1 exited with code 0
db-1     | 2024-02-20 03:23:52.992 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-20 03:23:52.999 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-20 03:23:53.001 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-20 03:23:53.001 UTC [64] LOG:  shutting down
db-1     | 2024-02-20 03:23:53.004 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-20 03:23:53.058 UTC [64] LOG:  checkpoint complete: wrote 46 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.030 s, total=0.058 s; sync files=14, longest=0.007 s, average=0.003 s; distance=238 kB, estimate=238 kB; lsn=0/1957818, redo lsn=0/1957818
db-1     | 2024-02-20 03:23:53.062 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
