 api2 Pulling 
 api1 Pulling 
 api2 Pulled 
 api1 Pulled 
 Volume "vgdss_pgdata"  Creating
 Volume "vgdss_pgdata"  Created
 Container rinhadb  Creating
 Container rinhadb  Created
 Container rinha-api1  Creating
 Container rinha-api2  Creating
 Container rinha-api1  Created
 Container rinha-api2  Created
 Container rinha-nginx  Creating
 Container rinha-nginx  Created
Attaching to rinha-api1, rinha-api2, rinha-nginx, rinhadb
rinhadb      | The files belonging to this database system will be owned by user "postgres".
rinhadb      | This user must also own the server process.
rinhadb      | 
rinhadb      | The database cluster will be initialized with locale "en_US.utf8".
rinhadb      | The default database encoding has accordingly been set to "UTF8".
rinhadb      | The default text search configuration will be set to "english".
rinhadb      | 
rinhadb      | Data page checksums are disabled.
rinhadb      | 
rinhadb      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
rinhadb      | creating subdirectories ... ok
rinhadb      | selecting dynamic shared memory implementation ... posix
rinhadb      | selecting default max_connections ... 100
rinhadb      | selecting default shared_buffers ... 128MB
rinhadb      | selecting default time zone ... Etc/UTC
rinhadb      | creating configuration files ... ok
rinha-nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
rinha-nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
rinha-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
rinha-nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
rinhadb      | running bootstrap script ... ok
rinha-nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
rinha-nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
rinha-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
rinha-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
rinha-nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
rinhadb      | performing post-bootstrap initialization ... ok
rinha-api1   | INFO:     Started server process [7]
rinha-api1   | INFO:     Waiting for application startup.
rinha-api1   | INFO:     Application startup complete.
rinha-api1   | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
rinha-api2   | INFO:     Started server process [7]
rinha-api2   | INFO:     Waiting for application startup.
rinha-api2   | INFO:     Application startup complete.
rinha-api2   | INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
rinha-api1   | INFO:     127.0.0.1:35392 - "GET /clientes/1/extrato HTTP/1.1" 500 Internal Server Error
rinha-api2   | INFO:     127.0.0.1:55420 - "GET /clientes/1/extrato HTTP/1.1" 500 Internal Server Error
rinha-api2   | ERROR:    Exception in ASGI application
rinha-api2   | Traceback (most recent call last):
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
rinha-api2   |     result = await app(  # type: ignore[func-returns-value]
rinha-api2   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
rinha-api2   |     return await self.app(scope, receive, send)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
rinha-api2   |     await super().__call__(scope, receive, send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
rinha-api2   |     await self.middleware_stack(scope, receive, send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
rinha-api2   |     raise exc
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
rinha-api2   |     await self.app(scope, receive, _send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
rinha-api2   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
rinha-api2   |     raise exc
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
rinha-api2   |     await app(scope, receive, sender)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
rinha-api2   |     await self.middleware_stack(scope, receive, send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
rinha-api2   |     await route.handle(scope, receive, send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
rinha-api2   |     await self.app(scope, receive, send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
rinha-api2   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
rinha-api2   |     raise exc
rinha-api1   | ERROR:    Exception in ASGI application
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
rinha-api2   |     await app(scope, receive, sender)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
rinha-api2   |     response = await func(request)
rinha-api2   |                ^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
rinha-api2   |     raw_response = await run_endpoint_function(
rinha-api2   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
rinha-api2   |     return await dependant.call(**values)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/home/app/api/crebito/routes/clientes.py", line 50, in get_extrato
rinha-api2   |     resultado = await session.execute(
rinha-api2   |                 ^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
rinha-api2   |     result = await greenlet_spawn(
rinha-api2   |              ^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 197, in greenlet_spawn
rinha-api2   |     result = context.throw(*sys.exc_info())
rinha-api2   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
rinha-api2   |     return self._execute_internal(
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
rinha-api2   |     conn = self._connection_for_bind(bind)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
rinha-api2   |     return trans._connection_for_bind(engine, execution_options)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "<string>", line 2, in _connection_for_bind
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
rinha-api2   |     ret_value = fn(self, *arg, **kw)
rinha-api2   |                 ^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
rinha-api2   |     conn = bind.connect()
rinha-api2   |            ^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3258, in connect
rinha-api2   |     return self._connection_cls(self)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
rinha-api2   |     self._dbapi_connection = engine.raw_connection()
rinha-api2   |                              ^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
rinha-api2   |     return self.pool.connect()
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
rinha-api2   |     return _ConnectionFairy._checkout(self)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
rinha-api2   |     fairy = _ConnectionRecord.checkout(pool)
rinha-api2   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   | Traceback (most recent call last):
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
rinha-api1   |     result = await app(  # type: ignore[func-returns-value]
rinha-api1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
rinha-api1   |     return await self.app(scope, receive, send)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
rinha-api1   |     await super().__call__(scope, receive, send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
rinha-api1   |     await self.middleware_stack(scope, receive, send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
rinha-api1   |     raise exc
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
rinha-api1   |     await self.app(scope, receive, _send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
rinha-api1   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
rinha-api1   |     raise exc
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
rinha-api1   |     await app(scope, receive, sender)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
rinha-api1   |     await self.middleware_stack(scope, receive, send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
rinha-api1   |     await route.handle(scope, receive, send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
rinha-api1   |     await self.app(scope, receive, send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
rinha-api1   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
rinha-api1   |     raise exc
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
rinha-api1   |     await app(scope, receive, sender)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
rinha-api1   |     response = await func(request)
rinha-api1   |                ^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
rinha-api1   |     raw_response = await run_endpoint_function(
rinha-api1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
rinha-api1   |     return await dependant.call(**values)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/home/app/api/crebito/routes/clientes.py", line 50, in get_extrato
rinha-api1   |     resultado = await session.execute(
rinha-api1   |                 ^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
rinha-api1   |     result = await greenlet_spawn(
rinha-api1   |              ^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 197, in greenlet_spawn
rinha-api1   |     result = context.throw(*sys.exc_info())
rinha-api1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
rinha-api1   |     return self._execute_internal(
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
rinha-api1   |     conn = self._connection_for_bind(bind)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
rinha-api1   |     return trans._connection_for_bind(engine, execution_options)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "<string>", line 2, in _connection_for_bind
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
rinha-api1   |     ret_value = fn(self, *arg, **kw)
rinha-api1   |                 ^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
rinha-api1   |     conn = bind.connect()
rinha-api1   |            ^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3258, in connect
rinha-api1   |     return self._connection_cls(self)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
rinha-api1   |     self._dbapi_connection = engine.raw_connection()
rinha-api1   |                              ^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
rinha-api1   |     return self.pool.connect()
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
rinha-api1   |     return _ConnectionFairy._checkout(self)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
rinha-api1   |     fairy = _ConnectionRecord.checkout(pool)
rinha-api1   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
rinha-api1   |     rec = pool._do_get()
rinha-api1   |           ^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
rinha-api1   |     with util.safe_reraise():
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
rinha-api1   |     raise exc_value.with_traceback(exc_tb)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
rinha-api1   |     return self._create_connection()
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
rinha-api1   |     return _ConnectionRecord(self)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
rinha-api1   |     self.__connect()
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
rinha-api1   |     with util.safe_reraise():
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
rinha-api1   |     raise exc_value.with_traceback(exc_tb)
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
rinha-api1   |     self.dbapi_connection = connection = pool._invoke_creator(self)
rinha-api1   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
rinha-api1   |     return dialect.connect(*cargs, **cparams)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
rinha-api1   |     return self.loaded_dbapi.connect(*cargs, **cparams)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 937, in connect
rinha-api1   |     await_only(creator_fn(*arg, **kw)),
rinha-api1   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
rinha-api1   |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
rinha-api1   |     value = await result
rinha-api1   |             ^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 2329, in connect
rinha-api1   |     return await connect_utils._connect(
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
rinha-api1   |     raise last_error or exceptions.TargetServerAttributeNotMatched(
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 991, in _connect
rinha-api1   |     conn = await _connect_addr(
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
rinha-api1   |     return await __connect_addr(params, True, *args)
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
rinha-api1   |     tr, pr = await connector
rinha-api1   |              ^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
rinha-api1   |     tr, pr = await loop.create_connection(
rinha-api1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1119, in create_connection
rinha-api1   |     raise exceptions[0]
rinha-api1   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1101, in create_connection
rinha-api1   |     sock = await self._connect_sock(
rinha-api1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1004, in _connect_sock
rinha-api1   |     await self.sock_connect(sock, address)
rinha-api1   |   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 647, in sock_connect
rinha-api1   |     return await fut
rinha-api1   |            ^^^^^^^^^
rinha-api1   |   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 687, in _sock_connect_cb
rinha-api1   |     raise OSError(err, f'Connect call failed {address}')
rinha-api1   | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5432)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
rinha-api2   |     rec = pool._do_get()
rinha-api2   |           ^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
rinha-api2   |     with util.safe_reraise():
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
rinha-api2   |     raise exc_value.with_traceback(exc_tb)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
rinha-api2   |     return self._create_connection()
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
rinha-api2   |     return _ConnectionRecord(self)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
rinha-api2   |     self.__connect()
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
rinha-api2   |     with util.safe_reraise():
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
rinha-api2   |     raise exc_value.with_traceback(exc_tb)
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
rinha-api2   |     self.dbapi_connection = connection = pool._invoke_creator(self)
rinha-api2   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
rinha-api2   |     return dialect.connect(*cargs, **cparams)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
rinha-api2   |     return self.loaded_dbapi.connect(*cargs, **cparams)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 937, in connect
rinha-api2   |     await_only(creator_fn(*arg, **kw)),
rinha-api2   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
rinha-api2   |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
rinha-api2   |     value = await result
rinha-api2   |             ^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 2329, in connect
rinha-api2   |     return await connect_utils._connect(
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
rinha-api2   |     raise last_error or exceptions.TargetServerAttributeNotMatched(
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 991, in _connect
rinha-api2   |     conn = await _connect_addr(
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
rinha-api2   |     return await __connect_addr(params, True, *args)
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
rinha-api2   |     tr, pr = await connector
rinha-api2   |              ^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
rinha-api2   |     tr, pr = await loop.create_connection(
rinha-api2   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1119, in create_connection
rinha-api2   |     raise exceptions[0]
rinha-api2   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1101, in create_connection
rinha-api2   |     sock = await self._connect_sock(
rinha-api2   |            ^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1004, in _connect_sock
rinha-api2   |     await self.sock_connect(sock, address)
rinha-api2   |   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 647, in sock_connect
rinha-api2   |     return await fut
rinha-api2   |            ^^^^^^^^^
rinha-api2   |   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 687, in _sock_connect_cb
rinha-api2   |     raise OSError(err, f'Connect call failed {address}')
rinha-api2   | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5432)
rinhadb      | syncing data to disk ... ok
rinhadb      | 
rinhadb      | 
rinhadb      | Success. You can now start the database server using:
rinhadb      | 
rinhadb      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
rinhadb      | 
rinhadb      | initdb: warning: enabling "trust" authentication for local connections
rinhadb      | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
rinhadb      | waiting for server to start.... done
rinhadb      | server started
rinhadb      | CREATE DATABASE
rinhadb      | 
rinhadb      | 
rinhadb      | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
rinhadb      | CREATE TABLE
rinhadb      | CREATE TABLE
rinhadb      | CREATE INDEX
rinhadb      | CREATE INDEX
rinhadb      | INSERT 0 5
rinhadb      | 
rinhadb      | 
rinhadb      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/postgresql.conf
rinhadb      | 
rinhadb      | waiting for server to shut down.... done
rinhadb      | server stopped
rinhadb      | 
rinhadb      | PostgreSQL init process complete; ready for start up.
rinhadb      | 
rinha-api2   | INFO:     127.0.0.1:55436 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55436 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55436 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55452 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55634 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55498 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55526 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55646 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55622 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55556 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55572 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55696 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55484 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55680 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55642 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55470 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55468 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55596 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55584 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55510 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55658 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55704 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55548 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55548 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55548 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55658 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55704 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55634 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55484 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55510 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55572 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55498 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55584 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55646 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55526 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55596 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55556 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55436 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55642 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55468 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55680 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55470 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55452 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55622 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55696 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55696 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55696 - "GET /clientes/6/extrato HTTP/1.1" 404 Not Found
rinha-api2   | INFO:     127.0.0.1:55622 - "GET /clientes/3/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "GET /clientes/5/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "GET /clientes/2/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "GET /clientes/4/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "POST /clientes/5/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "POST /clientes/2/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "POST /clientes/4/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55622 - "POST /clientes/3/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "POST /clientes/4/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55622 - "POST /clientes/3/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "POST /clientes/2/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "POST /clientes/5/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55622 - "GET /clientes/2/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "GET /clientes/5/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "GET /clientes/4/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "GET /clientes/3/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "POST /clientes/2/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "POST /clientes/1/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "POST /clientes/5/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "POST /clientes/3/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55622 - "POST /clientes/4/transacoes HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55622 - "GET /clientes/5/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55466 - "GET /clientes/4/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55666 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55608 - "GET /clientes/2/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55538 - "GET /clientes/5/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55696 - "GET /clientes/5/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55452 - "GET /clientes/5/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55680 - "GET /clientes/2/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55470 - "GET /clientes/2/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55468 - "GET /clientes/2/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55468 - "POST /clientes/5/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55470 - "POST /clientes/2/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55470 - "POST /clientes/5/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55468 - "POST /clientes/2/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55646 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55468 - "POST /clientes/5/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55470 - "POST /clientes/2/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55470 - "POST /clientes/5/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55468 - "POST /clientes/2/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55468 - "POST /clientes/5/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55470 - "POST /clientes/2/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55498 - "GET /clientes/3/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55642 - "GET /clientes/4/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55596 - "GET /clientes/3/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55556 - "GET /clientes/4/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55572 - "GET /clientes/3/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55436 - "GET /clientes/4/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55526 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55584 - "GET /clientes/1/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55584 - "POST /clientes/4/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55584 - "POST /clientes/4/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55510 - "GET /clientes/3/extrato HTTP/1.1" 200 OK
rinha-api2   | INFO:     127.0.0.1:55510 - "POST /clientes/4/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55584 - "POST /clientes/3/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55526 - "POST /clientes/1/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55526 - "POST /clientes/4/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55584 - "POST /clientes/3/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55510 - "POST /clientes/1/transacoes HTTP/1.1" 422 Unprocessable Entity
rinha-api2   | INFO:     127.0.0.1:55510 - "POST /clientes/4/transacoes HTTP/1.1" 422 Unprocessable Entity
