 Network felipebossolani-dotnet9-preview_app-network  Creating
 Network felipebossolani-dotnet9-preview_app-network  Created
 Container db  Creating
 Container db  Created
 Container api2  Creating
 Container api1  Creating
 Container api2  Created
 Container api1  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api1, api2, db, nginx
db     | The files belonging to this database system will be owned by user "postgres".
db     | This user must also own the server process.
db     | 
db     | The database cluster will be initialized with locale "en_US.utf8".
db     | The default database encoding has accordingly been set to "UTF8".
db     | The default text search configuration will be set to "english".
db     | 
db     | Data page checksums are disabled.
db     | 
db     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db     | creating subdirectories ... ok
db     | selecting dynamic shared memory implementation ... posix
db     | selecting default max_connections ... 100
db     | selecting default shared_buffers ... 128MB
db     | selecting default time zone ... Etc/UTC
db     | creating configuration files ... ok
db     | running bootstrap script ... ok
db     | performing post-bootstrap initialization ... ok
db     | syncing data to disk ... ok
db     | 
db     | 
db     | Success. You can now start the database server using:
db     | 
db     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db     | 
db     | initdb: warning: enabling "trust" authentication for local connections
db     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db     | waiting for server to start....2024-02-24 00:56:42.543 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db     | 2024-02-24 00:56:42.543 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db     | 2024-02-24 00:56:42.545 UTC [51] LOG:  database system was shut down at 2024-02-24 00:56:41 UTC
db     | 2024-02-24 00:56:42.548 UTC [48] LOG:  database system is ready to accept connections
db     |  done
db     | server started
db     | CREATE DATABASE
db     | 
db     | 
db     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01_ddl.sql
db     | CREATE TABLE
db     | CREATE TABLE
db     | ALTER TABLE
db     | CREATE INDEX
db     | 
db     | 
db     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/02_dml.sql
db     | DELETE 0
db     | DELETE 0
db     | INSERT 0 5
db     | CREATE FUNCTION
db     | 
db     | 
db     | waiting for server to shut down...2024-02-24 00:56:42.851 UTC [48] LOG:  received fast shutdown request
db     | .2024-02-24 00:56:42.851 UTC [48] LOG:  aborting any active transactions
db     | 2024-02-24 00:56:42.852 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db     | 2024-02-24 00:56:42.915 UTC [49] LOG:  shutting down
db     | 2024-02-24 00:56:42.915 UTC [49] LOG:  checkpoint starting: shutdown immediate
db     | 2024-02-24 00:56:42.921 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.007 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4287 kB, estimate=4287 kB; lsn=0/191A7E8, redo lsn=0/191A7E8
db     | 2024-02-24 00:56:42.928 UTC [48] LOG:  database system is shut down
db     |  done
db     | server stopped
db     | 
db     | PostgreSQL init process complete; ready for start up.
db     | 
db     | 2024-02-24 00:56:42.977 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db     | 2024-02-24 00:56:42.978 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db     | 2024-02-24 00:56:42.978 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db     | 2024-02-24 00:56:42.978 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db     | 2024-02-24 00:56:42.979 UTC [68] LOG:  database system was shut down at 2024-02-24 00:56:42 UTC
db     | 2024-02-24 00:56:42.982 UTC [1] LOG:  database system is ready to accept connections
db     | 2024-02-24 00:56:45.290 UTC [78] FATAL:  role "rinha" does not exist
nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
api2   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
api2   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8080'.
nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
api1   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
api1   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8080'.
nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
api2   | info: Microsoft.Hosting.Lifetime[14]
api2   |       Now listening on: http://[::]:8080
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Application started. Press Ctrl+C to shut down.
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Hosting environment: Production
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Content root path: /app
api1   | info: Microsoft.Hosting.Lifetime[14]
api1   |       Now listening on: http://[::]:8080
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Application started. Press Ctrl+C to shut down.
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Hosting environment: Production
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Content root path: /app
db     | 2024-02-24 00:56:50.382 UTC [86] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:56:53 [error] 30#30: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:56:53 [error] 29#29: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:56:53 [error] 31#31: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:56:53 [error] 31#31: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:56:55 [error] 32#32: *64 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:56:55.449 UTC [108] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:57:00.529 UTC [115] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:04 [error] 29#29: *338 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:04 [error] 31#31: *357 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:05 [error] 30#30: *390 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:57:05.602 UTC [123] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:06 [error] 32#32: *431 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:57:10.676 UTC [130] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:15 [error] 29#29: *1106 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:15 [error] 31#31: *1129 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:57:15.746 UTC [137] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:16 [error] 30#30: *1290 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:17 [error] 32#32: *1323 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:57:20.814 UTC [144] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:57:25.895 UTC [152] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:26 [error] 31#31: *2554 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:26 [error] 29#29: *2637 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:27 [error] 30#30: *2720 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:28 [error] 32#32: *2987 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:57:30.970 UTC [159] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:57:36.043 UTC [166] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:37 [error] 29#29: *4690 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:37 [error] 31#31: *4721 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/2/extrato HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/extrato", host: "localhost:9999"
nginx  | 2024/02/24 00:57:38 [error] 30#30: *4910 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:39 [error] 32#32: *5171 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:57:41.124 UTC [173] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:57:46.207 UTC [181] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:48 [error] 29#29: *7508 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:48 [error] 31#31: *7541 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:49 [error] 30#30: *7830 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:57:50 [error] 32#32: *8121 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:57:51.283 UTC [188] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:57:56.363 UTC [195] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:57:59 [error] 29#29: *10972 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/2/extrato HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/extrato", host: "localhost:9999"
nginx  | 2024/02/24 00:57:59 [error] 31#31: *11001 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:00 [error] 30#30: *11418 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:01 [error] 32#32: *11707 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:01.435 UTC [202] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:58:06.523 UTC [210] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:58:10 [error] 29#29: *15196 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:10 [error] 31#31: *15229 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:11 [error] 30#30: *15646 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:11.615 UTC [217] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:58:12 [error] 32#32: *16049 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:16.715 UTC [224] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:58:21 [error] 31#31: *19982 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:21 [error] 29#29: *20065 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:21.818 UTC [231] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:58:22 [error] 30#30: *20514 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:23 [error] 32#32: *20935 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:26.917 UTC [240] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:58:32.018 UTC [247] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:58:32 [error] 29#29: *25572 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:32 [error] 31#31: *25575 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:33 [error] 30#30: *26044 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:34 [error] 32#32: *26585 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:37.122 UTC [254] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:58:42.223 UTC [261] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:58:43 [error] 29#29: *31720 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:43 [error] 31#31: *31753 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:44 [error] 30#30: *32314 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:45 [error] 32#32: *32971 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:47.322 UTC [270] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:58:52.428 UTC [277] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:58:54 [error] 29#29: *38636 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:54 [error] 31#31: *38669 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:55 [error] 30#30: *39334 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:58:56 [error] 32#32: *40011 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:58:57.528 UTC [284] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:59:02.625 UTC [291] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:05 [error] 29#29: *46066 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:05 [error] 31#31: *46081 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:06 [error] 30#30: *46756 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:07 [error] 32#32: *47443 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:07.725 UTC [299] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:59:12.825 UTC [306] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:16 [error] 29#29: *53512 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:16 [error] 31#31: *53533 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:17 [error] 30#30: *54198 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:17.924 UTC [313] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:18 [error] 32#32: *54881 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:23.025 UTC [320] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:27 [error] 29#29: *61048 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:27 [error] 31#31: *61081 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:28 [error] 30#30: *61753 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:28.129 UTC [340] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:29 [error] 32#32: *62427 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:33.227 UTC [347] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:38 [error] 29#29: *68484 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:38 [error] 31#31: *68511 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:38.324 UTC [355] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:39 [error] 30#30: *69178 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:40 [error] 32#32: *69859 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:43.429 UTC [363] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:59:48.529 UTC [370] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 00:59:49 [error] 31#31: *75968 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:49 [error] 29#29: *76017 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:50 [error] 30#30: *76736 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 00:59:51 [error] 32#32: *77402 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 00:59:53.627 UTC [378] FATAL:  role "rinha" does not exist
db     | 2024-02-24 00:59:58.729 UTC [385] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:00 [error] 29#29: *83463 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:00 [error] 31#31: *83477 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:01 [error] 30#30: *84164 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:02 [error] 32#32: *84819 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/2/extrato HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/extrato", host: "localhost:9999"
db     | 2024-02-24 01:00:03.825 UTC [393] FATAL:  role "rinha" does not exist
db     | 2024-02-24 01:00:08.925 UTC [401] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:11 [error] 31#31: *90936 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:11 [error] 29#29: *91009 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/5/extrato HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/extrato", host: "localhost:9999"
nginx  | 2024/02/24 01:00:12 [error] 30#30: *91612 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:13 [error] 32#32: *92299 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-24 01:00:14.026 UTC [408] FATAL:  role "rinha" does not exist
db     | 2024-02-24 01:00:19.130 UTC [415] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:22 [error] 29#29: *98431 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:22 [error] 31#31: *98463 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:23 [error] 30#30: *99150 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:24 [error] 32#32: *99813 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-24 01:00:24.230 UTC [423] FATAL:  role "rinha" does not exist
db     | 2024-02-24 01:00:29.325 UTC [431] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:33 [error] 29#29: *105904 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:33 [error] 31#31: *105916 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:34 [error] 30#30: *106586 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 01:00:34.429 UTC [438] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:35 [error] 32#32: *107261 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-24 01:00:39.529 UTC [445] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:44 [error] 29#29: *113418 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:44 [error] 31#31: *113454 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-24 01:00:44.632 UTC [453] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:45 [error] 30#30: *114134 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:46 [error] 32#32: *114793 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-24 01:00:49.733 UTC [460] FATAL:  role "rinha" does not exist
db     | 2024-02-24 01:00:54.831 UTC [467] FATAL:  role "rinha" does not exist
nginx  | 2024/02/24 01:00:55 [error] 29#29: *120872 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:55 [error] 31#31: *120890 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:56 [error] 30#30: *121559 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/24 01:00:57 [error] 32#32: *122235 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.80.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-24 01:00:59.897 UTC [474] FATAL:  role "rinha" does not exist
nginx exited with code 0
nginx exited with code 0
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Application is shutting down...
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Application is shutting down...
api1 exited with code 0
api1 exited with code 0
api2 exited with code 0
api2 exited with code 0
db     | 2024-02-24 01:01:02.380 UTC [1] LOG:  received fast shutdown request
db     | 2024-02-24 01:01:02.381 UTC [1] LOG:  aborting any active transactions
db     | 2024-02-24 01:01:02.383 UTC [1] LOG:  background worker "logical replication launcher" (PID 71) exited with exit code 1
db     | 2024-02-24 01:01:02.383 UTC [66] LOG:  shutting down
db     | 2024-02-24 01:01:02.383 UTC [66] LOG:  checkpoint starting: shutdown immediate
db     | 2024-02-24 01:01:02.387 UTC [66] LOG:  checkpoint complete: wrote 870 buffers (5.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=2885 kB, estimate=2885 kB; lsn=0/1BEBFD0, redo lsn=0/1BEBFD0
db     | 2024-02-24 01:01:02.393 UTC [1] LOG:  database system is shut down
db exited with code 0
