 Network rinha-backend  Creating
 Network rinha-backend  Created
 Container fbourguignon-crdb-1  Creating
 Container fbourguignon-crdb-1  Created
 Container fbourguignon-api2-1  Creating
 Container fbourguignon-api1-1  Creating
 Container fbourguignon-api1-1  Created
 Container fbourguignon-api2-1  Created
 Container fbourguignon-nginx-1  Creating
 Container fbourguignon-nginx-1  Created
Attaching to api1-1, api2-1, crdb-1, nginx-1
crdb-1   | ls: cannot access 'cockroach-data': No such file or directory
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api1-1   |  __  __ _                                  _   
api1-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api1-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api1-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api1-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
api2-1   |  __  __ _                                  _   
api2-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api2-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api2-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api2-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
crdb-1   | certificate dir "certs" is successfully set up
crdb-1   | starting node for the initialization process. This could take a couple seconds...
crdb-1   | *
crdb-1   | * WARNING: ALL SECURITY CONTROLS HAVE BEEN DISABLED!
crdb-1   | * 
crdb-1   | * This mode is intended for non-production testing only.
crdb-1   | * 
crdb-1   | * In this mode:
crdb-1   | * - Your cluster is open to any client that can access any of your IP addresses.
crdb-1   | * - Intruders with access to your machine or network can observe client-server traffic.
crdb-1   | * - Intruders can log in without password and read or write any data in the cluster.
crdb-1   | * - Intruders can consume all your server's resources and cause unavailability.
crdb-1   | *
crdb-1   | *
crdb-1   | * INFO: To start a secure server without mandating TLS for clients,
crdb-1   | * consider --accept-sql-without-tls instead. For other options, see:
crdb-1   | * 
crdb-1   | * - https://go.crdb.dev/issue-v/53404/v23.2
crdb-1   | * - https://www.cockroachlabs.com/docs/v23.2/secure-a-cluster.html
crdb-1   | *
crdb-1   | *
crdb-1   | * WARNING: the sum of --max-sql-memory (75 MiB), --cache (128 MiB), and --max-tsdb-memory (64 MiB) is larger than 75% of total RAM (225 MiB).
crdb-1   | * This server is running at increased risk of memory-related failures.
crdb-1   | *
crdb-1   | *
crdb-1   | * WARNING: --max-sql-memory (75 MiB) is set too low, consider increasing it
crdb-1   | *
crdb-1   | *
crdb-1   | * WARNING: Running a server without --sql-addr, with a combined RPC/SQL listener, is deprecated.
crdb-1   | * This feature will be removed in a later version of CockroachDB.
crdb-1   | *
crdb-1   | init node successfully started
crdb-1   | /cockroach/cockroach.sh: line 201:    65 Killed                  $cockroach_entrypoint sql --url="$(cat server.url)" "$@"
crdb-1   | /cockroach/cockroach.sh: line 203:    48 Killed                  "${start_node_query[@]}"
crdb-1   | ERROR: cannot dial server.
crdb-1   | Is the server running?
crdb-1   | If the server is running, check --host client-side and --advertise server-side.
crdb-1   | 
crdb-1   | failed to connect to `host=127.0.0.1 user=root database=defaultdb`: dial error (dial tcp 127.0.0.1:26257: connect: connection refused)
crdb-1   | Failed running "sql"
crdb-1 exited with code 1
api2-1   | [36m02:14:10.427[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api1-1   | [36m02:14:10.635[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api2-1   | [36m02:14:11.654[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
api2-1   | 	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
api2-1   | 	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
api2-1   | 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
api2-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:326)
api2-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:312)
api2-1   | 	at br.com.rinhabackend.Application.main(Application.java:8)
api2-1   | Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2345)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
api2-1   | 	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
api2-1   | 	... 9 common frames omitted
api2-1   | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
api2-1   | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.instantiate(Unknown Source)
api2-1   | 	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
api2-1   | 	... 16 common frames omitted
api2-1   | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
api2-1   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api2-1   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api2-1   | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api2-1   | 	at org.postgresql.Driver.connect(Driver.java:297)
api2-1   | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
api2-1   | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
api2-1   | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
api2-1   | 	... 23 common frames omitted
api2-1   | Caused by: java.net.UnknownHostException: crdb
api2-1   | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
api2-1   | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
api2-1   | 	at java.base/java.net.Socket.connect(Unknown Source)
api2-1   | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api2-1   | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api2-1   | 	... 32 common frames omitted
api1-1   | [36m02:14:11.839[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
api1-1   | 	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
api1-1   | 	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
api1-1   | 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
api1-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:326)
api1-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:312)
api1-1   | 	at br.com.rinhabackend.Application.main(Application.java:8)
api1-1   | Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2345)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
api1-1   | 	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
api1-1   | 	... 9 common frames omitted
api1-1   | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
api1-1   | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.instantiate(Unknown Source)
api1-1   | 	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
api1-1   | 	... 16 common frames omitted
api1-1   | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
api1-1   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api1-1   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api1-1   | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api1-1   | 	at org.postgresql.Driver.connect(Driver.java:297)
api1-1   | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
api1-1   | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
api1-1   | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
api1-1   | 	... 23 common frames omitted
api1-1   | Caused by: java.net.UnknownHostException: crdb
api1-1   | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
api1-1   | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
api1-1   | 	at java.base/java.net.Socket.connect(Unknown Source)
api1-1   | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api1-1   | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api1-1   | 	... 32 common frames omitted
api2-1 exited with code 0
api1-1 exited with code 0
api1-1   |  __  __ _                                  _   
api1-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api1-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api1-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api1-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
api2-1   |  __  __ _                                  _   
api2-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api2-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api2-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api2-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
api1-1   | [36m02:14:19.436[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api2-1   | [36m02:14:19.627[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api1-1   | [36m02:14:20.718[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
api1-1   | 	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
api1-1   | 	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
api1-1   | 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
api1-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:326)
api1-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:312)
api1-1   | 	at br.com.rinhabackend.Application.main(Application.java:8)
api1-1   | Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2345)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
api1-1   | 	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
api1-1   | 	... 9 common frames omitted
api1-1   | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
api1-1   | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.instantiate(Unknown Source)
api1-1   | 	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
api1-1   | 	... 16 common frames omitted
api1-1   | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
api1-1   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api1-1   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api1-1   | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api1-1   | 	at org.postgresql.Driver.connect(Driver.java:297)
api1-1   | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
api1-1   | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
api1-1   | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
api1-1   | 	... 23 common frames omitted
api1-1   | Caused by: java.net.UnknownHostException: crdb
api1-1   | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
api1-1   | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
api1-1   | 	at java.base/java.net.Socket.connect(Unknown Source)
api1-1   | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api1-1   | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api1-1   | 	... 32 common frames omitted
api2-1   | [36m02:14:20.844[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
api2-1   | 	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
api2-1   | 	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
api2-1   | 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
api2-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:326)
api2-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:312)
api2-1   | 	at br.com.rinhabackend.Application.main(Application.java:8)
api2-1   | Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2345)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
api2-1   | 	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
api2-1   | 	... 9 common frames omitted
api2-1   | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
api2-1   | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.instantiate(Unknown Source)
api2-1   | 	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
api2-1   | 	... 16 common frames omitted
api2-1   | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
api2-1   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api2-1   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api2-1   | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api2-1   | 	at org.postgresql.Driver.connect(Driver.java:297)
api2-1   | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
api2-1   | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
api2-1   | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
api2-1   | 	... 23 common frames omitted
api2-1   | Caused by: java.net.UnknownHostException: crdb
api2-1   | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
api2-1   | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
api2-1   | 	at java.base/java.net.Socket.connect(Unknown Source)
api2-1   | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api2-1   | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api2-1   | 	... 32 common frames omitted
api1-1 exited with code 0
api2-1 exited with code 0
api1-1   |  __  __ _                                  _   
api2-1   |  __  __ _                                  _   
api2-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api2-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api2-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api2-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
api1-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api1-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api1-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api1-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
api2-1   | [36m02:14:28.539[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api1-1   | [36m02:14:28.631[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api2-1   | [36m02:14:29.733[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
api2-1   | 	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
api2-1   | 	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
api2-1   | 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
api2-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:326)
api2-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:312)
api2-1   | 	at br.com.rinhabackend.Application.main(Application.java:8)
api2-1   | Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]
api2-1   | 
api2-1   | Message: Failed to initialize pool: The connection attempt failed.
api2-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2345)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
api2-1   | 	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
api2-1   | 	... 9 common frames omitted
api2-1   | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
api2-1   | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
api2-1   | 	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.instantiate(Unknown Source)
api2-1   | 	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
api2-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
api2-1   | 	... 16 common frames omitted
api2-1   | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
api2-1   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api2-1   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api2-1   | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api2-1   | 	at org.postgresql.Driver.connect(Driver.java:297)
api2-1   | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
api2-1   | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
api2-1   | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
api2-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
api2-1   | 	... 23 common frames omitted
api2-1   | Caused by: java.net.UnknownHostException: crdb
api2-1   | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
api2-1   | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
api2-1   | 	at java.base/java.net.Socket.connect(Unknown Source)
api2-1   | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api2-1   | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api2-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api2-1   | 	... 32 common frames omitted
api1-1   | [36m02:14:29.841[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
api1-1   | 	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
api1-1   | 	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
api1-1   | 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
api1-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:326)
api1-1   | 	at io.micronaut.runtime.Micronaut.run(Micronaut.java:312)
api1-1   | 	at br.com.rinhabackend.Application.main(Application.java:8)
api1-1   | Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2345)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
api1-1   | 	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
api1-1   | 	... 9 common frames omitted
api1-1   | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
api1-1   | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
api1-1   | 	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.instantiate(Unknown Source)
api1-1   | 	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
api1-1   | 	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
api1-1   | 	... 16 common frames omitted
api1-1   | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
api1-1   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api1-1   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api1-1   | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api1-1   | 	at org.postgresql.Driver.connect(Driver.java:297)
api1-1   | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
api1-1   | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
api1-1   | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
api1-1   | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
api1-1   | 	... 23 common frames omitted
api1-1   | Caused by: java.net.UnknownHostException: crdb
api1-1   | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
api1-1   | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
api1-1   | 	at java.base/java.net.Socket.connect(Unknown Source)
api1-1   | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api1-1   | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api1-1   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api1-1   | 	... 32 common frames omitted
api2-1 exited with code 0
api1-1 exited with code 0
api2-1   |  __  __ _                                  _   
api2-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api2-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api2-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api2-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
api1-1   |  __  __ _                                  _   
api1-1   | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
api1-1   | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
api1-1   | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
api1-1   | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
api1-1   | [36m02:14:37.126[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api2-1   | [36m02:14:37.431[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mcom.zaxxer.hikari.HikariDataSource[0;39m - HikariPool-1 - Starting...
api1-1   | [36m02:14:38.421[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
api1-1   | Message: Failed to initialize pool: The connection attempt failed.
api1-1   | Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration)
api1-1   | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
api1-1   | 
