 Network diego-coronel_default  Creating
 Network diego-coronel_default  Created
 Container postgres  Creating
 Container postgres  Created
 Container api2  Creating
 Container api1  Creating
 Container api1  Created
 Container api2  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api1, api2, nginx, postgres
postgres  | The files belonging to this database system will be owned by user "postgres".
postgres  | This user must also own the server process.
postgres  | 
postgres  | The database cluster will be initialized with locale "en_US.utf8".
postgres  | The default database encoding has accordingly been set to "UTF8".
postgres  | The default text search configuration will be set to "english".
postgres  | 
postgres  | Data page checksums are disabled.
postgres  | 
postgres  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres  | creating subdirectories ... ok
postgres  | selecting dynamic shared memory implementation ... posix
postgres  | selecting default max_connections ... 100
postgres  | selecting default shared_buffers ... 128MB
postgres  | selecting default time zone ... Etc/UTC
postgres  | creating configuration files ... ok
postgres  | running bootstrap script ... ok
api2      | __  ____  __  _____   ___  __ ____  ______ 
api2      |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api2      |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api2      | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api2      | 2024-02-11 16:05:20,999 INFO  [io.quarkus] (main) rinha-2024 1.0-SNAPSHOT native (powered by Quarkus 3.7.2) started in 0.076s. Listening on: http://0.0.0.0:8080
api2      | 2024-02-11 16:05:20,999 INFO  [io.quarkus] (main) Profile prod activated. 
api2      | 2024-02-11 16:05:20,999 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, jdbc-postgresql, kotlin, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
api1      | __  ____  __  _____   ___  __ ____  ______ 
api1      |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api1      |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api1      | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api1      | 2024-02-11 16:05:21,010 INFO  [io.quarkus] (main) rinha-2024 1.0-SNAPSHOT native (powered by Quarkus 3.7.2) started in 0.027s. Listening on: http://0.0.0.0:8080
api1      | 2024-02-11 16:05:21,014 INFO  [io.quarkus] (main) Profile prod activated. 
api1      | 2024-02-11 16:05:21,014 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, jdbc-postgresql, kotlin, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
nginx     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx     | /docker-entrypoint.sh: Configuration complete; ready for start up
postgres  | performing post-bootstrap initialization ... ok
postgres  | syncing data to disk ... ok
postgres  | 
postgres  | 
postgres  | Success. You can now start the database server using:
postgres  | 
postgres  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres  | 
postgres  | initdb: warning: enabling "trust" authentication for local connections
postgres  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres  | waiting for server to start....2024-02-11 16:05:22.393 UTC [48] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres  | 2024-02-11 16:05:22.405 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2024-02-11 16:05:22.432 UTC [51] LOG:  database system was shut down at 2024-02-11 16:05:21 UTC
postgres  | 2024-02-11 16:05:22.447 UTC [48] LOG:  database system is ready to accept connections
api1      | 2024-02-11 16:05:22,455 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
postgres  |  done
postgres  | server started
api1      | 2024-02-11 16:05:22,456 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /clientes/1/extrato failed, error id: b119762d-fd3d-4222-a2c6-ae49593b1fa2-1: org.jboss.resteasy.spi.UnhandledException: org.jooq.exception.DataAccessException: Error getting connection from data source io.agroal.pool.DataSource@7a2f5e01
api1      | 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:107)
api1      | 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:344)
api1      | 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:205)
api1      | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
api1      | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
api1      | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
api1      | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
api1      | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
api1      | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
api1      | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
api1      | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
api1      | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
api1      | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
api1      | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
api1      | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
api1      | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
api1      | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
api1      | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1      | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api1      | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api1      | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api1      | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api1      | Caused by: org.jooq.exception.DataAccessException: Error getting connection from data source io.agroal.pool.DataSource@7a2f5e01
api1      | 	at org.jooq_3.18.3.POSTGRES.debug(Unknown Source)
api1      | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90)
api1      | 	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:620)
api1      | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:308)
api1      | 	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
api1      | 	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
api1      | 	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2862)
api1      | 	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
api1      | 	at br.rinha.resource.ClienteResource.extrato(ClienteResource.kt:66)
api1      | 	at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
api1      | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
api1      | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
api1      | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
api1      | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
api1      | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
api1      | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
api1      | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
api1      | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
api1      | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
api1      | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
api1      | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
api1      | 	... 18 more
api1      | Caused by: org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api1      | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api1      | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api1      | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api1      | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api1      | 	at org.postgresql.Driver.connect(Driver.java:297)
api1      | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
api1      | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
api1      | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
api1      | 	at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
api1      | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
api1      | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api1      | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
api1      | 	... 4 more
api1      | Caused by: java.net.ConnectException: Connection refused
api1      | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api1      | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api1      | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api1      | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api1      | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api1      | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api1      | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api1      | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api1      | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api1      | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api1      | 	... 15 more
api1      | 
postgres  | CREATE DATABASE
postgres  | 
postgres  | 
postgres  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
postgres  | CREATE TABLE
postgres  | CREATE TABLE
postgres  | CREATE INDEX
postgres  | CREATE INDEX
postgres  | INSERT 0 1
postgres  | INSERT 0 1
postgres  | INSERT 0 1
postgres  | INSERT 0 1
postgres  | INSERT 0 1
postgres  | 
postgres  | 
postgres  | 2024-02-11 16:05:22.768 UTC [48] LOG:  received fast shutdown request
postgres  | waiting for server to shut down....2024-02-11 16:05:22.770 UTC [48] LOG:  aborting any active transactions
postgres  | 2024-02-11 16:05:22.798 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
postgres  | 2024-02-11 16:05:22.800 UTC [49] LOG:  shutting down
postgres  | 2024-02-11 16:05:22.811 UTC [49] LOG:  checkpoint starting: shutdown immediate
postgres  | 2024-02-11 16:05:22.934 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.079 s, sync=0.035 s, total=0.134 s; sync files=313, longest=0.004 s, average=0.001 s; distance=4288 kB, estimate=4288 kB; lsn=0/191AA20, redo lsn=0/191AA20
postgres  | 2024-02-11 16:05:22.943 UTC [48] LOG:  database system is shut down
postgres  |  done
postgres  | server stopped
postgres  | 
postgres  | PostgreSQL init process complete; ready for start up.
postgres  | 
postgres  | 2024-02-11 16:05:23.004 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres  | 2024-02-11 16:05:23.005 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres  | 2024-02-11 16:05:23.005 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres  | 2024-02-11 16:05:23.011 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2024-02-11 16:05:23.020 UTC [66] LOG:  database system was shut down at 2024-02-11 16:05:22 UTC
postgres  | 2024-02-11 16:05:23.028 UTC [1] LOG:  database system is ready to accept connections
api1      | 2024-02-11 16:05:24,481 INFO  [org.joo.imp.Def.logVersionSupport] (executor-thread-1) Version                  : Database version is supported by dialect POSTGRES: 16.1 (Debian 16.1-1.pgdg120+1)
api2      | 2024-02-11 16:05:32,420 INFO  [org.joo.imp.Def.logVersionSupport] (executor-thread-1) Version                  : Database version is supported by dialect POSTGRES: 16.1 (Debian 16.1-1.pgdg120+1)
postgres  | 2024-02-11 16:05:45.298 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:45.298 UTC [70] DETAIL:  Failing row contains (2, 80000, -84056, 1).
postgres  | 2024-02-11 16:05:45.298 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:45.759 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:45.759 UTC [73] DETAIL:  Failing row contains (2, 80000, -88414, 1).
postgres  | 2024-02-11 16:05:45.759 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:46.048 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:46.048 UTC [72] DETAIL:  Failing row contains (2, 80000, -86181, 1).
postgres  | 2024-02-11 16:05:46.048 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:46.377 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:46.377 UTC [71] DETAIL:  Failing row contains (2, 80000, -80762, 1).
postgres  | 2024-02-11 16:05:46.377 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:46.537 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:46.537 UTC [71] DETAIL:  Failing row contains (2, 80000, -85491, 1).
postgres  | 2024-02-11 16:05:46.537 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:48.636 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:48.636 UTC [73] DETAIL:  Failing row contains (2, 80000, -83950, 1).
postgres  | 2024-02-11 16:05:48.636 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:48.808 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:48.808 UTC [73] DETAIL:  Failing row contains (1, 100000, -103889, 1).
postgres  | 2024-02-11 16:05:48.808 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:49.188 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:49.188 UTC [73] DETAIL:  Failing row contains (1, 100000, -106499, 1).
postgres  | 2024-02-11 16:05:49.188 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:49.222 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:49.222 UTC [73] DETAIL:  Failing row contains (2, 80000, -84208, 1).
postgres  | 2024-02-11 16:05:49.222 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:49.322 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:49.322 UTC [71] DETAIL:  Failing row contains (2, 80000, -86870, 1).
postgres  | 2024-02-11 16:05:49.322 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:49.966 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:49.966 UTC [73] DETAIL:  Failing row contains (2, 80000, -81654, 1).
postgres  | 2024-02-11 16:05:49.966 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:49.999 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:49.999 UTC [71] DETAIL:  Failing row contains (2, 80000, -80833, 1).
postgres  | 2024-02-11 16:05:49.999 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:50.317 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:50.317 UTC [71] DETAIL:  Failing row contains (1, 100000, -105088, 1).
postgres  | 2024-02-11 16:05:50.317 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:50.408 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:50.408 UTC [71] DETAIL:  Failing row contains (1, 100000, -104582, 1).
postgres  | 2024-02-11 16:05:50.408 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:50.499 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:50.499 UTC [70] DETAIL:  Failing row contains (1, 100000, -101509, 1).
postgres  | 2024-02-11 16:05:50.499 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:52.689 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:52.689 UTC [73] DETAIL:  Failing row contains (2, 80000, -80170, 1).
postgres  | 2024-02-11 16:05:52.689 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:53.413 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:53.413 UTC [73] DETAIL:  Failing row contains (2, 80000, -81531, 1).
postgres  | 2024-02-11 16:05:53.413 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:53.545 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:53.545 UTC [71] DETAIL:  Failing row contains (2, 80000, -81146, 1).
postgres  | 2024-02-11 16:05:53.545 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:53.913 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:53.913 UTC [71] DETAIL:  Failing row contains (2, 80000, -84026, 1).
postgres  | 2024-02-11 16:05:53.913 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.357 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.357 UTC [71] DETAIL:  Failing row contains (1, 100000, -106813, 1).
postgres  | 2024-02-11 16:05:54.357 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.407 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.407 UTC [71] DETAIL:  Failing row contains (1, 100000, -100198, 1).
postgres  | 2024-02-11 16:05:54.407 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.481 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.481 UTC [72] DETAIL:  Failing row contains (2, 80000, -82647, 1).
postgres  | 2024-02-11 16:05:54.481 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.557 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.557 UTC [70] DETAIL:  Failing row contains (1, 100000, -102080, 1).
postgres  | 2024-02-11 16:05:54.557 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.607 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.607 UTC [70] DETAIL:  Failing row contains (2, 80000, -87244, 1).
postgres  | 2024-02-11 16:05:54.607 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.632 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.632 UTC [72] DETAIL:  Failing row contains (1, 100000, -101086, 1).
postgres  | 2024-02-11 16:05:54.632 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.832 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.832 UTC [70] DETAIL:  Failing row contains (2, 80000, -84119, 1).
postgres  | 2024-02-11 16:05:54.832 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:54.882 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:54.882 UTC [70] DETAIL:  Failing row contains (2, 80000, -82271, 1).
postgres  | 2024-02-11 16:05:54.882 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.007 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.007 UTC [70] DETAIL:  Failing row contains (1, 100000, -104082, 1).
postgres  | 2024-02-11 16:05:55.007 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.303 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.303 UTC [73] DETAIL:  Failing row contains (1, 100000, -102695, 1).
postgres  | 2024-02-11 16:05:55.303 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.327 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.327 UTC [72] DETAIL:  Failing row contains (1, 100000, -100148, 1).
postgres  | 2024-02-11 16:05:55.327 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.422 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.422 UTC [73] DETAIL:  Failing row contains (2, 80000, -83762, 1).
postgres  | 2024-02-11 16:05:55.422 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.470 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.470 UTC [72] DETAIL:  Failing row contains (2, 80000, -83149, 1).
postgres  | 2024-02-11 16:05:55.470 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.494 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.494 UTC [72] DETAIL:  Failing row contains (1, 100000, -104948, 1).
postgres  | 2024-02-11 16:05:55.494 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.565 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.565 UTC [72] DETAIL:  Failing row contains (1, 100000, -107402, 1).
postgres  | 2024-02-11 16:05:55.565 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.757 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.757 UTC [73] DETAIL:  Failing row contains (2, 80000, -84452, 1).
postgres  | 2024-02-11 16:05:55.757 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.780 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.780 UTC [73] DETAIL:  Failing row contains (2, 80000, -81143, 1).
postgres  | 2024-02-11 16:05:55.780 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.803 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.803 UTC [73] DETAIL:  Failing row contains (2, 80000, -88419, 1).
postgres  | 2024-02-11 16:05:55.803 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.876 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.876 UTC [72] DETAIL:  Failing row contains (2, 80000, -80015, 1).
postgres  | 2024-02-11 16:05:55.876 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:55.970 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:55.970 UTC [72] DETAIL:  Failing row contains (2, 80000, -83753, 1).
postgres  | 2024-02-11 16:05:55.970 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:56.160 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:56.160 UTC [72] DETAIL:  Failing row contains (2, 80000, -85265, 1).
postgres  | 2024-02-11 16:05:56.160 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:56.643 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:56.643 UTC [72] DETAIL:  Failing row contains (1, 100000, -105225, 1).
postgres  | 2024-02-11 16:05:56.643 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:56.733 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:56.733 UTC [72] DETAIL:  Failing row contains (2, 80000, -84230, 1).
postgres  | 2024-02-11 16:05:56.733 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:56.802 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:56.802 UTC [73] DETAIL:  Failing row contains (2, 80000, -81108, 1).
postgres  | 2024-02-11 16:05:56.802 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:56.961 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:56.961 UTC [72] DETAIL:  Failing row contains (2, 80000, -85032, 1).
postgres  | 2024-02-11 16:05:56.961 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:56.984 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:56.984 UTC [72] DETAIL:  Failing row contains (2, 80000, -86269, 1).
postgres  | 2024-02-11 16:05:56.984 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:57.075 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:57.075 UTC [73] DETAIL:  Failing row contains (2, 80000, -85267, 1).
postgres  | 2024-02-11 16:05:57.075 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:57.166 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:57.166 UTC [70] DETAIL:  Failing row contains (2, 80000, -81102, 1).
postgres  | 2024-02-11 16:05:57.166 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:57.778 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:57.778 UTC [71] DETAIL:  Failing row contains (2, 80000, -82971, 1).
postgres  | 2024-02-11 16:05:57.778 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:57.842 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:57.842 UTC [71] DETAIL:  Failing row contains (2, 80000, -84410, 1).
postgres  | 2024-02-11 16:05:57.842 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.017 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.017 UTC [72] DETAIL:  Failing row contains (2, 80000, -85144, 1).
postgres  | 2024-02-11 16:05:58.017 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.298 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.298 UTC [70] DETAIL:  Failing row contains (1, 100000, -103781, 1).
postgres  | 2024-02-11 16:05:58.298 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.490 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.490 UTC [70] DETAIL:  Failing row contains (2, 80000, -81728, 1).
postgres  | 2024-02-11 16:05:58.490 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.511 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.511 UTC [70] DETAIL:  Failing row contains (1, 100000, -101155, 1).
postgres  | 2024-02-11 16:05:58.511 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.596 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.596 UTC [72] DETAIL:  Failing row contains (1, 100000, -106375, 1).
postgres  | 2024-02-11 16:05:58.596 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.681 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.681 UTC [72] DETAIL:  Failing row contains (1, 100000, -107719, 1).
postgres  | 2024-02-11 16:05:58.681 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.745 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.745 UTC [70] DETAIL:  Failing row contains (2, 80000, -85176, 1).
postgres  | 2024-02-11 16:05:58.745 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.830 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.830 UTC [70] DETAIL:  Failing row contains (2, 80000, -81819, 1).
postgres  | 2024-02-11 16:05:58.830 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.851 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.851 UTC [72] DETAIL:  Failing row contains (2, 80000, -82113, 1).
postgres  | 2024-02-11 16:05:58.851 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:58.873 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:58.873 UTC [72] DETAIL:  Failing row contains (2, 80000, -87087, 1).
postgres  | 2024-02-11 16:05:58.873 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:59.656 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:59.656 UTC [70] DETAIL:  Failing row contains (1, 100000, -101122, 1).
postgres  | 2024-02-11 16:05:59.656 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:59.816 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:59.816 UTC [70] DETAIL:  Failing row contains (2, 80000, -80140, 1).
postgres  | 2024-02-11 16:05:59.816 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:59.856 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:59.856 UTC [70] DETAIL:  Failing row contains (2, 80000, -83727, 1).
postgres  | 2024-02-11 16:05:59.856 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:59.956 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:59.956 UTC [70] DETAIL:  Failing row contains (2, 80000, -81175, 1).
postgres  | 2024-02-11 16:05:59.956 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:05:59.976 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:05:59.976 UTC [72] DETAIL:  Failing row contains (2, 80000, -82341, 1).
postgres  | 2024-02-11 16:05:59.976 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.196 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.196 UTC [71] DETAIL:  Failing row contains (1, 100000, -106792, 1).
postgres  | 2024-02-11 16:06:00.196 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.236 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.236 UTC [70] DETAIL:  Failing row contains (2, 80000, -82286, 1).
postgres  | 2024-02-11 16:06:00.236 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.355 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.355 UTC [70] DETAIL:  Failing row contains (2, 80000, -83260, 1).
postgres  | 2024-02-11 16:06:00.355 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.374 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.374 UTC [70] DETAIL:  Failing row contains (1, 100000, -103242, 1).
postgres  | 2024-02-11 16:06:00.374 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.452 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.452 UTC [70] DETAIL:  Failing row contains (1, 100000, -105912, 1).
postgres  | 2024-02-11 16:06:00.452 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.530 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.530 UTC [70] DETAIL:  Failing row contains (2, 80000, -80302, 1).
postgres  | 2024-02-11 16:06:00.530 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.590 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.590 UTC [72] DETAIL:  Failing row contains (2, 80000, -84281, 1).
postgres  | 2024-02-11 16:06:00.590 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.648 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.648 UTC [72] DETAIL:  Failing row contains (2, 80000, -85065, 1).
postgres  | 2024-02-11 16:06:00.648 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.668 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.668 UTC [70] DETAIL:  Failing row contains (2, 80000, -85900, 1).
postgres  | 2024-02-11 16:06:00.668 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.707 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.707 UTC [72] DETAIL:  Failing row contains (2, 80000, -82042, 1).
postgres  | 2024-02-11 16:06:00.707 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:00.864 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:00.864 UTC [70] DETAIL:  Failing row contains (2, 80000, -87522, 1).
postgres  | 2024-02-11 16:06:00.864 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.021 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.021 UTC [70] DETAIL:  Failing row contains (2, 80000, -84592, 1).
postgres  | 2024-02-11 16:06:01.021 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.080 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.080 UTC [70] DETAIL:  Failing row contains (2, 80000, -83978, 1).
postgres  | 2024-02-11 16:06:01.080 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.217 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.217 UTC [70] DETAIL:  Failing row contains (2, 80000, -85841, 1).
postgres  | 2024-02-11 16:06:01.217 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.274 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.274 UTC [72] DETAIL:  Failing row contains (2, 80000, -85362, 1).
postgres  | 2024-02-11 16:06:01.274 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.312 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.312 UTC [73] DETAIL:  Failing row contains (2, 80000, -82639, 1).
postgres  | 2024-02-11 16:06:01.312 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.388 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.388 UTC [73] DETAIL:  Failing row contains (1, 100000, -101765, 1).
postgres  | 2024-02-11 16:06:01.388 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.520 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.520 UTC [73] DETAIL:  Failing row contains (1, 100000, -102906, 1).
postgres  | 2024-02-11 16:06:01.520 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.539 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.539 UTC [73] DETAIL:  Failing row contains (1, 100000, -108760, 1).
postgres  | 2024-02-11 16:06:01.539 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.595 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.595 UTC [72] DETAIL:  Failing row contains (1, 100000, -104892, 1).
postgres  | 2024-02-11 16:06:01.595 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.689 UTC [73] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.689 UTC [73] DETAIL:  Failing row contains (1, 100000, -105985, 1).
postgres  | 2024-02-11 16:06:01.689 UTC [73] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:01.785 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:01.785 UTC [72] DETAIL:  Failing row contains (1, 100000, -100265, 1).
postgres  | 2024-02-11 16:06:01.785 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.142 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.142 UTC [72] DETAIL:  Failing row contains (1, 100000, -101197, 1).
postgres  | 2024-02-11 16:06:02.142 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.256 UTC [72] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.256 UTC [72] DETAIL:  Failing row contains (2, 80000, -80617, 1).
postgres  | 2024-02-11 16:06:02.256 UTC [72] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.274 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.274 UTC [70] DETAIL:  Failing row contains (1, 100000, -100443, 1).
postgres  | 2024-02-11 16:06:02.274 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.328 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.328 UTC [71] DETAIL:  Failing row contains (2, 80000, -80497, 1).
postgres  | 2024-02-11 16:06:02.328 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.384 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.384 UTC [71] DETAIL:  Failing row contains (1, 100000, -101309, 1).
postgres  | 2024-02-11 16:06:02.384 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.401 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.401 UTC [71] DETAIL:  Failing row contains (1, 100000, -103485, 1).
postgres  | 2024-02-11 16:06:02.401 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.420 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.420 UTC [70] DETAIL:  Failing row contains (1, 100000, -101847, 1).
postgres  | 2024-02-11 16:06:02.420 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.529 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.529 UTC [71] DETAIL:  Failing row contains (1, 100000, -103012, 1).
postgres  | 2024-02-11 16:06:02.529 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.583 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.583 UTC [70] DETAIL:  Failing row contains (1, 100000, -105428, 1).
postgres  | 2024-02-11 16:06:02.583 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.675 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.675 UTC [70] DETAIL:  Failing row contains (2, 80000, -83125, 1).
postgres  | 2024-02-11 16:06:02.675 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.692 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.692 UTC [70] DETAIL:  Failing row contains (2, 80000, -86871, 1).
postgres  | 2024-02-11 16:06:02.692 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:02.856 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:02.856 UTC [71] DETAIL:  Failing row contains (2, 80000, -86412, 1).
postgres  | 2024-02-11 16:06:02.856 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:03.092 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:03.092 UTC [71] DETAIL:  Failing row contains (2, 80000, -84051, 1).
postgres  | 2024-02-11 16:06:03.092 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:03.129 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:03.129 UTC [70] DETAIL:  Failing row contains (2, 80000, -84536, 1).
postgres  | 2024-02-11 16:06:03.129 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:03.541 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:03.541 UTC [70] DETAIL:  Failing row contains (2, 80000, -82113, 1).
postgres  | 2024-02-11 16:06:03.541 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:03.792 UTC [70] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:03.792 UTC [70] DETAIL:  Failing row contains (2, 80000, -88468, 1).
postgres  | 2024-02-11 16:06:03.792 UTC [70] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:03.827 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:03.827 UTC [71] DETAIL:  Failing row contains (2, 80000, -88858, 1).
postgres  | 2024-02-11 16:06:03.827 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:03.845 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:03.845 UTC [71] DETAIL:  Failing row contains (2, 80000, -87882, 1).
postgres  | 2024-02-11 16:06:03.845 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:03.898 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:03.898 UTC [71] DETAIL:  Failing row contains (2, 80000, -86336, 1).
postgres  | 2024-02-11 16:06:03.898 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:04.459 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:04.459 UTC [71] DETAIL:  Failing row contains (2, 80000, -81322, 1).
postgres  | 2024-02-11 16:06:04.459 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:04.493 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:04.493 UTC [71] DETAIL:  Failing row contains (2, 80000, -82562, 1).
postgres  | 2024-02-11 16:06:04.493 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
postgres  | 2024-02-11 16:06:04.645 UTC [71] ERROR:  new row for relation "cliente" violates check constraint "saldo_limite_check"
postgres  | 2024-02-11 16:06:04.645 UTC [71] DETAIL:  Failing row contains (2, 80000, -86448, 1).
postgres  | 2024-02-11 16:06:04.645 UTC [71] STATEMENT:  update "cliente" set "saldo" = ("cliente"."saldo" - $1) where "cliente"."id" = $2 returning "cliente"."limite", "cliente"."saldo"
