 Network felipebossolani-dotnet_app-network  Creating
 Network felipebossolani-dotnet_app-network  Created
 Container db  Creating
 Container db  Created
 Container api1  Creating
 Container api2  Creating
 Container api1  Created
 Container api2  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api1, api2, db, nginx
db     | The files belonging to this database system will be owned by user "postgres".
db     | This user must also own the server process.
db     | 
db     | The database cluster will be initialized with locale "en_US.utf8".
db     | The default database encoding has accordingly been set to "UTF8".
db     | The default text search configuration will be set to "english".
db     | 
db     | Data page checksums are disabled.
db     | 
db     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db     | creating subdirectories ... ok
db     | selecting dynamic shared memory implementation ... posix
db     | selecting default max_connections ... 100
db     | selecting default shared_buffers ... 128MB
db     | selecting default time zone ... Etc/UTC
db     | creating configuration files ... ok
db     | running bootstrap script ... ok
db     | performing post-bootstrap initialization ... ok
db     | initdb: warning: enabling "trust" authentication for local connections
db     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db     | syncing data to disk ... ok
db     | 
db     | 
db     | Success. You can now start the database server using:
db     | 
db     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db     | 
db     | waiting for server to start....2024-02-18 02:24:53.245 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db     | 2024-02-18 02:24:53.245 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db     | 2024-02-18 02:24:53.247 UTC [51] LOG:  database system was shut down at 2024-02-18 02:24:51 UTC
db     | 2024-02-18 02:24:53.250 UTC [48] LOG:  database system is ready to accept connections
db     |  done
db     | server started
db     | CREATE DATABASE
db     | 
db     | 
db     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01_ddl.sql
db     | CREATE TABLE
db     | CREATE TABLE
db     | ALTER TABLE
db     | CREATE INDEX
db     | 
db     | 
db     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/02_dml.sql
db     | DELETE 0
db     | DELETE 0
db     | INSERT 0 5
db     | CREATE FUNCTION
db     | 
db     | 
db     | waiting for server to shut down....2024-02-18 02:24:53.553 UTC [48] LOG:  received fast shutdown request
db     | 2024-02-18 02:24:53.553 UTC [48] LOG:  aborting any active transactions
db     | 2024-02-18 02:24:53.615 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db     | 2024-02-18 02:24:53.615 UTC [49] LOG:  shutting down
db     | 2024-02-18 02:24:53.615 UTC [49] LOG:  checkpoint starting: shutdown immediate
db     | 2024-02-18 02:24:53.621 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.006 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4287 kB, estimate=4287 kB; lsn=0/191A7E8, redo lsn=0/191A7E8
db     | 2024-02-18 02:24:53.628 UTC [48] LOG:  database system is shut down
db     |  done
db     | server stopped
db     | 
db     | PostgreSQL init process complete; ready for start up.
db     | 
db     | 2024-02-18 02:24:53.679 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db     | 2024-02-18 02:24:53.679 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db     | 2024-02-18 02:24:53.679 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db     | 2024-02-18 02:24:53.680 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db     | 2024-02-18 02:24:53.681 UTC [68] LOG:  database system was shut down at 2024-02-18 02:24:53 UTC
db     | 2024-02-18 02:24:53.684 UTC [1] LOG:  database system is ready to accept connections
db     | 2024-02-18 02:24:55.920 UTC [78] FATAL:  role "rinha" does not exist
nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
api1   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
api1   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8080'.
nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
api2   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
api2   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8080'.
api1   | info: Microsoft.Hosting.Lifetime[14]
api1   |       Now listening on: http://[::]:8080
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Application started. Press Ctrl+C to shut down.
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Hosting environment: Production
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Content root path: /app
api2   | info: Microsoft.Hosting.Lifetime[14]
api2   |       Now listening on: http://[::]:8080
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Application started. Press Ctrl+C to shut down.
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Hosting environment: Production
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Content root path: /app
db     | 2024-02-18 02:25:01.016 UTC [86] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:04 [error] 30#30: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:04 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:04 [error] 29#29: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:04 [error] 31#31: *52 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:25:06.090 UTC [104] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:25:11.177 UTC [123] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:15 [error] 32#32: *293 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:15 [error] 31#31: *314 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:25:16.256 UTC [131] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:16 [error] 29#29: *346 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:17 [error] 30#30: *380 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:25:21.333 UTC [138] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:26 [error] 32#32: *1053 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:26 [error] 31#31: *1081 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:25:26.418 UTC [146] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:27 [error] 29#29: *1247 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:28 [error] 30#30: *1280 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:25:31.486 UTC [153] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:25:36.563 UTC [161] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:37 [error] 32#32: *2491 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:37 [error] 31#31: *2498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:38 [error] 29#29: *2659 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:39 [error] 30#30: *2826 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:25:41.641 UTC [168] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:25:46.714 UTC [175] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:48 [error] 32#32: *4645 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:48 [error] 31#31: *4681 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:49 [error] 29#29: *4839 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:50 [error] 30#30: *5128 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:25:51.822 UTC [182] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:25:56.895 UTC [190] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:25:59 [error] 32#32: *7465 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:25:59 [error] 31#31: *7498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:00 [error] 29#29: *7787 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:01 [error] 30#30: *8076 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:01.972 UTC [196] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:26:07.043 UTC [203] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:10 [error] 32#32: *10925 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:10 [error] 31#31: *10958 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:11 [error] 29#29: *11247 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:12.129 UTC [210] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:12 [error] 30#30: *11664 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:17.215 UTC [219] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:21 [error] 32#32: *15045 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/5/extrato HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/extrato", host: "localhost:9999"
nginx  | 2024/02/18 02:26:21 [error] 31#31: *15058 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:22 [error] 29#29: *15475 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:22.291 UTC [226] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:23 [error] 30#30: *15892 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:27.368 UTC [233] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:32 [error] 32#32: *19895 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:32 [error] 31#31: *19926 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:32.456 UTC [240] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:33 [error] 29#29: *20353 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:34 [error] 30#30: *20888 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:37.539 UTC [249] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:26:42.622 UTC [256] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:43 [error] 32#32: *25401 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:43 [error] 31#31: *25434 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:44 [error] 29#29: *25979 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/3/extrato HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/extrato", host: "localhost:9999"
nginx  | 2024/02/18 02:26:45 [error] 30#30: *26524 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:47.722 UTC [263] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:26:52.821 UTC [270] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:26:54 [error] 31#31: *31593 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:54 [error] 32#32: *31666 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:55 [error] 29#29: *32255 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:26:56 [error] 30#30: *32802 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:26:57.918 UTC [278] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:27:03.024 UTC [285] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:27:05 [error] 32#32: *38473 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:05 [error] 31#31: *38498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:06 [error] 29#29: *39171 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:07 [error] 30#30: *39844 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:27:08.126 UTC [292] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:27:13.225 UTC [299] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:27:16 [error] 32#32: *45905 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:16 [error] 31#31: *45926 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/5/extrato HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/extrato", host: "localhost:9999"
nginx  | 2024/02/18 02:27:17 [error] 29#29: *46601 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:18 [error] 30#30: *47274 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:27:18.324 UTC [308] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:27:23.423 UTC [315] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:27:27 [error] 32#32: *53449 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:27 [error] 31#31: *53474 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:28 [error] 29#29: *54143 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:27:28.522 UTC [322] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:27:29 [error] 30#30: *54828 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:27:33.622 UTC [329] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:27:38 [error] 32#32: *60881 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:38 [error] 31#31: *60897 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/4/extrato HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/extrato", host: "localhost:9999"
db     | 2024-02-18 02:27:38.727 UTC [337] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:27:39 [error] 29#29: *61583 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:40 [error] 30#30: *62252 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:27:43.827 UTC [345] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:27:48.922 UTC [352] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:27:49 [error] 31#31: *68351 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:49 [error] 32#32: *68435 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:50 [error] 29#29: *69035 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:27:51 [error] 30#30: *69716 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:27:54.022 UTC [360] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:27:59.127 UTC [367] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:00 [error] 32#32: *75851 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:00 [error] 31#31: *75884 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:01 [error] 29#29: *76545 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:02 [error] 30#30: *77227 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "GET /clientes/2/extrato HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/extrato", host: "localhost:9999"
db     | 2024-02-18 02:28:04.226 UTC [374] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:28:09.328 UTC [381] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:11 [error] 32#32: *83319 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:11 [error] 31#31: *83328 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:12 [error] 29#29: *84004 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:13 [error] 30#30: *84684 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:28:14.427 UTC [390] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:28:19.527 UTC [397] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:22 [error] 32#32: *90847 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:22 [error] 31#31: *90875 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:23 [error] 29#29: *91551 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:24 [error] 30#30: *92224 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:28:24.623 UTC [404] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:28:29.726 UTC [411] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:33 [error] 32#32: *98289 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:33 [error] 31#31: *98308 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:34 [error] 29#29: *98981 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:28:34.825 UTC [419] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:35 [error] 30#30: *99659 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:28:39.928 UTC [426] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:44 [error] 32#32: *105825 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:44 [error] 31#31: *105864 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:28:45.028 UTC [434] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:45 [error] 29#29: *106519 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:46 [error] 30#30: *107200 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:28:50.131 UTC [441] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:55 [error] 32#32: *113257 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:55 [error] 31#31: *113277 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:28:55.229 UTC [450] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:28:56 [error] 29#29: *113947 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:28:57 [error] 30#30: *114639 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:29:00.325 UTC [457] FATAL:  role "rinha" does not exist
db     | 2024-02-18 02:29:05.432 UTC [464] FATAL:  role "rinha" does not exist
nginx  | 2024/02/18 02:29:06 [error] 31#31: *120739 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:29:06 [error] 32#32: *120816 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:29:07 [error] 29#29: *121515 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/18 02:29:08 [error] 30#30: *122180 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.144.4:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-18 02:29:10.519 UTC [471] FATAL:  role "rinha" does not exist
nginx exited with code 0
nginx exited with code 0
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Application is shutting down...
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Application is shutting down...
api1 exited with code 0
api1 exited with code 0
api2 exited with code 0
api2 exited with code 0
db     | 2024-02-18 02:29:13.517 UTC [1] LOG:  received fast shutdown request
db     | 2024-02-18 02:29:13.518 UTC [1] LOG:  aborting any active transactions
db     | 2024-02-18 02:29:13.520 UTC [1] LOG:  background worker "logical replication launcher" (PID 71) exited with exit code 1
db     | 2024-02-18 02:29:13.520 UTC [66] LOG:  shutting down
db     | 2024-02-18 02:29:13.520 UTC [66] LOG:  checkpoint starting: shutdown immediate
db     | 2024-02-18 02:29:13.524 UTC [66] LOG:  checkpoint complete: wrote 870 buffers (5.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=2850 kB, estimate=2850 kB; lsn=0/1BE33C8, redo lsn=0/1BE33C8
db     | 2024-02-18 02:29:13.530 UTC [1] LOG:  database system is shut down
db exited with code 0
